/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Health: () => import('#controllers/health_controller'),
  Home: () => import('#controllers/home_controller'),
  Pdf: () => import('#controllers/pdf_controller'),
}
